### ISSUE TITLE
lost libqminvapi_intermediates

### ISSUE THREAD

**Issue by talpachen** [morphicts/android_device_xiaomi_libra#1]
Hi,

I am trying to brunch cm_libra-userdebug, but lost libqminvapi_intermediates.

`make: *** No rule to make target '/home/llp/mnt/android/out/target/product/libra/obj/SHARED_LIBRARIES/libqminvapi_intermediates/export_includes', needed by '/home/llp/mnt/android/out/target/product/libra/obj/EXECUTABLES/readmac_intermediates/import_includes'.  Stop.
make: *** Waiting for unfinished jobs....`

Thanks

**Comment by morphicts** [comment]
Have you ran extract-files.sh ?

**Comment by morphicts** [comment]
I assume that was the problem. (because libqminvapi comes from propritary files)

**Comment by h4waii** [comment]
Didn't want to open another issue -- what path should this be extracting to?
