### ISSUE TITLE
TimeService APK Rule Missing...

### ISSUE THREAD

**Issue by ghost** [morphicts/android_device_xiaomi_libra#3]
Building from latest source;

make: **\* No rule to make target 'vendor/xiaomi/libra/proprietary/app/TimeService/TimeService.apk', needed by '/opt/CM/out/target/product/libra/system/app/TimeService/TimeService.apk'.  Stop.

The APK doesn't exist in the source directory.

**Comment by mikkonid** [comment]
It comes from proprietary-files.txt. You need to run extract-files.sh before build.
extract-files.sh takes path to miui folder as parameter. 
unzipped miui folder needs to have boot.img extracted to ./boot and system.dat to ./system

**Comment by morphicts** [comment]
It comes from proprietary-files.txt. You need to run extract-files.sh before build.
extract-files.sh takes path to miui folder as parameter. 
unzipped miui folder needs to have boot.img extracted to ./boot and system.dat to ./system
